Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import turtle
>>> t=turtle.Turtle()
>>> t.pensize(5)
>>> t.penup()
>>> t.goto(250,-250)
>>> t.fillcolor("brown")
>>> t.begin_fill()
>>> t.pendown()
>>> t.forward(50)
>>> t.left(90)
>>> t.forward(100)
>>> t.left(90)
>>> t.forward(50)
>>> t.left(90)
>>> t.forward(100)
>>> t.end_fill()
>>> t.penup()
>>> t.goto(225,-150)
>>> t.l(90)
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    t.l(90)
AttributeError: 'Turtle' object has no attribute 'l'
>>> t.left(90)
>>> t.fillcolor("green")
>>> t.pendown()
>>> t.begin_fill()
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.end_fill()
>>> t.penup()
>>> t.goto(225,-95)
>>> t.goto(225,-75)
>>> t.goto(225,-65)
>>> t.left(120)
>>> t.pendown()
>>> t.begin_fill()
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.end_fill()
>>> t.penup()
>>> t.goto(225,-20)
>>> t.goto(225,20)
>>> t.left(120)
>>> t.pendown()
>>> t.begin_fill()
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.end_fill()
SyntaxError: multiple statements found while compiling a single statement
>>> t.pendown()
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.end_fill()
SyntaxError: multiple statements found while compiling a single statement
>>> t.pendown()
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.left(120)
>>> t.forward(100)
>>> t.end_fill()
SyntaxError: multiple statements found while compiling a single statement
>>> t.left(120)
>>> t.forward(100)
>>> t.end_fill()
>>> t.penup()
>>> t.backward(100)
>>> t.fillcolor("yelow")
Traceback (most recent call last):
  File "<pyshell#62>", line 1, in <module>
    t.fillcolor("yelow")
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\turtle.py", line 2289, in fillcolor
    color = self._colorstr(args)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\turtle.py", line 2697, in _colorstr
    return self.screen._colorstr(args)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\turtle.py", line 1159, in _colorstr
    raise TurtleGraphicsError("bad color string: %s" % str(color))
turtle.TurtleGraphicsError: bad color string: yelow
>>> t.fillcolor("yellow")
>>> t.pendown()
>>> t.left(180)
>>> t.begin_fill()
>>> for i in range(20):
	t.forward(50)
	t.left(144)

>>> t.end_fill()
>>> t.penup()
>>> t.fillcolor("red")
>>> t.goto(150,150)
>>> t.goto(150,250)
>>> t.pendown()
>>> t.begin_fill()
>>> t.cirle(40)
Traceback (most recent call last):
  File "<pyshell#79>", line 1, in <module>
    t.cirle(40)
AttributeError: 'Turtle' object has no attribute 'cirle'
>>> t.circle(40)
>>> t.end_fill()
>>> t.pensize(1)
>>> t.fillcolor("black")
>>> t.right(90)
>>> t.forward(50)
>>> t.backward(180)
>>> t.forward(90)
>>> t.penup()
>>> t.right(60)
>>> t.forward(140)
>>> t.pendown()
>>> t.backward(280)
>>> t.forward(140)
>>> t.left(60)
>>> t.left(60)
>>> t.forward(140)
>>> t.backward(280)
>>> t.forward(100)
>>> t.penup()
>>> t.goto(150,250)
>>> t.circle(40)
>>> t.left(60)
>>> t.circle(40)
>>> t.right(15)
>>> t.circle(40)
>>> t.right(5)
>>> t.circle(40)
>>> t.right(2)
>>> t.circle(40)
>>> t.fillcolor("red")
>>> t.pendown()
>>> t.begin_fill()
>>> t.circle(40)
>>> t.end_fill()
>>> t.penup()
>>> t.goto(-250,-250)
>>> t.color("black")
>>> t.fillcolor("blue")
>>> t.right(60)
>>> t.right(2)
>>> t.right(5)
>>> t.pendown()
>>> t.begin_fill()
>>> t.forward(150)
>>> t.backward(150)
>>> t.right(5)
>>> t.pensize(5)
>>> t.forward(200)
>>> t.backward(200)
>>> t.left(3)
>>> t.forward(200)
>>> t.left(90)
>>> t.forward(300)
>>> t.left(90)
>>> t.forward(200)
>>> t.left(90)
>>> t.forward(300)
>>> t.end_fill()
>>> t.left(90)
>>> t.forward(75)
>>> t.fillcolor("green")
>>> t.begin_fill()
>>> t.forward(50)
>>> t.left(90)
>>> t.forward(150)
>>> t.left(90)
>>> t.forward(50)
>>> t.left(90)
>>> t.forward(150)
>>> t.end_fill()
>>> t.left(90)
>>> t.penup()
>>> t.forward(125)
>>> t.fillcolor("yellow")
>>> t.left(30)
>>> t.pendown()
>>> t.begin_fill()
>>> t.forward(200)
>>> t.left(90)
>>> t.right(30)
>>> t.forward(300)
>>> t.left(30)
>>> t.left(90)
>>> t.forward(200)
>>> t.end_fill()
>>> t.fillcolor("pink")
>>> t.right(60)
>>> t.right(30)
>>> t.begin_fill()
>>> t.forward(150)
>>> t.left(60)
>>> t.left(60)
>>> t.forward(150)
>>> t.backward(150)
>>> t.left(30)
>>> t.right(60)
>>> t.left(10)
>>> t.left(10)
>>> t.right(5)
>>> t.forward(150)
>>> t.forward(10)
>>> t.forward(10)
>>> t.forward(10)
>>> t.end_fill()
>>> t.penup()
>>> t.goto(250,-250)
>>> t.fillcolor("orange")
>>> t.forward(200)
>>> t.backward(200)
>>> t.goto(-250,-250)
>>> t.left(120)
>>> t.left(5)
>>> t.left(5)
>>> t.forward(200)
>>> t.backward(200)
>>> t.left(5)
>>> t.forward(200)
>>> t.left(90)
>>> t.forward(300)
>>> t.right(90)
>>> t.left(30)
>>> t.forward(200)
>>> t.left(120)
>>> t.right(60)
>>> t.left(30)
>>> t.right(15)
>>> t.left(15)
>>> t.begin_fill()
>>> t.pendown()
>>> t.forward(150)
>>> t.left(120)
>>> t.right(15)
>>> t.penup()
>>> t.forward(200)
>>> t.backward(200)
>>> t.right(15)
>>> t.forward(200)
>>> t.backward(200)
>>> t.pendown()
>>> t.forward(200)
>>> t.end_fill()
>>> t.begin_fill()
>>> t.left(90)
>>> t.forward(150)
>>> t.left(90)
>>> t.forward(200)
>>> t.end_fill()
>>> t.penup()
>>> t.right(120)
>>> t.goto(0,-50)
>>> t.goto(50,-50)
>>> t.goto(20,-70)
>>> t.left(90)
>>> t.left(30)
>>> t.pendown()
>>> t.fillcolor("red")
>>> t.begin_fill()
>>> t.forward(75)
>>> t.left(60)
>>> t.left(30)
>>> t.right(30)
>>> t.penup()
>>> t.forward(75)
>>> t.backward(75)
>>> t.pendown()
>>> t.forward(75)
>>> t.left(90)
>>> t.left(30)
>>> t.penup()
>>> t.forward(75)
>>> t.pendown()
>>> t.backward(75)
>>> t.forward(75)
>>> t.left(120)
>>> t.right(90)
>>> t.left(30)
>>> t.forward(75)
>>> t.end_fill()
>>> print"sun")
SyntaxError: invalid syntax
>>> print(sun)
Traceback (most recent call last):
  File "<pyshell#262>", line 1, in <module>
    print(sun)
NameError: name 'sun' is not defined
>>> 